<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap 101 Template</title>

        <!-- Bootstrap -->
        <link href="/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/twitter-bootstrap/layout.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header class="header navbar-static-top">
            <h1>Title of the first page</h1>
            <a href="index">Main</a>
        </header>
        <div class="container">
            <?php
            //            echo $this->renderControllerActionTemplate();

            $model = new Dv\Models\IndexModel();
            $model->displayFirstQuery();
            ?>
        </div>
        <div class="navbar-fixed-bottom footer">

        </div>

    </body>
</html>