<?php
    /** @var \Dv\Blocks\Fees\ListFees $this */
    $data = $this->getFeesList();
?>

<h1>Fees of actors between 40 and 60 years old</h1>
<table class="table">
    <?php foreach ($data as $row): ?>
        <tr>
            <td><?php echo $row['full name'] ?></td>
            <td><?php echo $row['fees'] ?></td>
            <td><?php echo $row['age'] ?></td>
        </tr>
    <?php endforeach; ?>
</table>