<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap 101 Template</title>

        <!-- Bootstrap -->
        <link href="/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/twitter-bootstrap/layout.css" rel="stylesheet">

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <![endif]-->
        <script type="text/javascript">
            $(document).ready(function(){
                $('.form1 select').on('change', function() {
                    var $form = $('.form1');
                    console.log($form.attr('action'));
                    var res = $.post(
                        $form.attr('action'), // ссылка куда отправляем данные
                        $(this).serialize(), // данные формы
                        function($response) {
                            $('.table-container').empty().append($response);
                        }
                    );
                    return false;
                });

            })
        </script>
    </head>
    <body>
        <header class="header navbar-static-top">
            <h1>Title of the second page</h1>
            <a href="index">Main</a>
        </header>
        <div class="container">
            <?php
            $model = new Dv\Models\IndexModel();
            $model->displaySecondQuery();

            ?>
        </div>
        <div class="navbar-fixed-bottom footer">

        </div>
    </body>
</html>
