<?php
    /** @var \Dv\Blocks\Studios\ListStudios $this */
    $data = $this->getStudiosList();
?>
<div class="studio-info">
    <h1>Information about the actors who starred for the studio</h1>
    <table class="table">
        <tr>
            <td>Title</td>
            <td>Full name</td>
            <td>Count films</td>
        </tr>
        <?php foreach ($data as $row): ?>
            <tr>
                <td><?php echo $row['title']; ?></td>
                <td><?php echo $row['full_name']; ?></td>
                <td><?php echo $row['count_films']; ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

